name: Release Workflow

on:
  repository_dispatch:
    types: [trigger-release]

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "nanuijaz"
          git config user.email "nanuijaz@users.noreply.github.com"

      - name: Get latest release version
        id: get-latest-release
        run: |
          latestTag=$(curl -s "https://api.github.com/repos/IntersectMBO/cardano-db-sync/releases/latest" | jq -r '.tag_name')
          echo "${latestTag}"
          echo "latestTag={$latestTag}" >> $GITHUB_OUTPUT

      - name: Create release in forked repository
        run: echo "${ steps.get-latest-release.outputs.latestTag }"

