name: Create Release in Forked Repository

on:
  release:
    types:
      - published

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "nanuijaz"
          git config user.email "nanuijaz@users.noreply.github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/IntersectMBO/cardano-db-sync

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Create release in forked repository
        run: |
          latestTag=$(git describe --tags --abbrev=0)
          git tag -a "v${{ github.event.release.tag_name }}" -m "${{ github.event.release.body }}"
          git push origin "v${{ github.event.release.tag_name }}"
